name: Convert String to Lowercase

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lowercase-string:
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment variables
        run: |
          # Here we set the uppercase string as an environment variable
          echo "UPPERCASE_STRING=HELLO WORLD" >> $GITHUB_ENV

      - name: Convert string to lowercase
        id: convert
        run: |
          # Convert the uppercase string to lowercase using awk
          echo "lowercase_string=$(echo ${{ env.UPPERCASE_STRING }} | awk '{print tolower($0)}')" >> $GITHUB_ENV

      - name: Print Lowercase String
        run: echo "Lowercase string is ${{ env.lowercase_string }}"