name: Convert String to Lowercase

on:
  push:
    branches:
      - dev_01
  workflow_dispatch:

jobs:
  lowercase-string:
    runs-on: ubuntu-latest

    steps:
      - name: Convert string to lowercase
        id: convert
        run: |
          echo "input_string=XIAOCHUN ------->" >> $GITHUB_ENV
          echo "lowercase_string=$(echo ${{ env.input_string }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Print Lowercase String
        run: echo "Lowercase string is ${{ env.lowercase_string }}"